# Job config to eval Llama 3.1 405B Instruct quantized on GCP.
#
# Requirements:
#   - Set up SkyPilot GCP: https://oumi.ai/docs/en/latest/user_guides/launch/launch.html#setup
#   - Log into WandB (`wandb login`) or disable `enable_wandb`
#   - Log into HF: `huggingface-cli login`

#
# Usage:
#   oumi launch up -c configs/recipes/llama3_1/evaluation/405b_quantized_gcp_job.yaml --cluster llama405b-quantized-eval
#
# See Also:
#   - Documentation: https://oumi.ai/docs/en/latest/user_guides/launch/launch.html
#   - Config class: oumi.core.configs.JobConfig
#   - Config source: https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/job_config.py
#   - Other job configs: configs/**/*job.yaml




name: llama405b-quantized-eval

resources:
  cloud: gcp
  accelerators: "A100:8"
  use_spot: false
  disk_size: 1000 

working_dir: .

file_mounts:
  ~/.netrc: ~/.netrc  # WandB credentials
  ~/.cache/huggingface/token: ~/.cache/huggingface/token # HF credentials

envs:
  # NOTE: For SFT, update this to point to your model checkpoint.
  # NOTE: For LoRA, instead update this to point to your LoRA adapter.
  #       The base model will be inferred automatically.
  MODEL_CHECKPOINT_DIR: neuralmagic/Meta-Llama-3.1-405B-Instruct-quantized.w8a8
  WANDB_PROJECT: oumi-eval
  OUMI_RUN_NAME: llama405b.quantized.eval

setup: |
  set -e
  pip install uv && uv pip install oumi[gpu,evaluation] hf_transfer
  # Install model from HF Hub. This tool increases download speed compared to
  # downloading the model during eval.
  HF_HUB_ENABLE_HF_TRANSFER=1 huggingface-cli download neuralmagic/Meta-Llama-3.1-405B-Instruct-quantized.w8a8 --exclude original/*

run: |
  set -e  # Exit if any command failed.
  source ./configs/examples/misc/sky_init.sh

  if test ${OUMI_NUM_NODES} -ne 1; then
    echo "LM Harness supports max 1 node. Actual: ${OUMI_NUM_NODES} nodes."
    exit 1
  fi

  echo "Starting evaluation for ${MODEL_CHECKPOINT_DIR} ..."
  set -x
  oumi distributed accelerate launch \
    -m oumi evaluate \
    -c configs/recipes/llama3_1/evaluation/405b_quantized_gcp_job.yaml \
    --run_name "${OUMI_RUN_NAME}.${SKYPILOT_TASK_ID}" \
    --model.model_name "${MODEL_CHECKPOINT_DIR}"

  echo "Node ${SKYPILOT_NODE_RANK} is all done!"


