

# Inference config for Llama 405B Instruct quantized.
#
# Requirements:
#   - Log into HF: `huggingface-cli login`
#   - Request access to Llama 3.1: https://huggingface.co/neuralmagic/Meta-Llama-3.1-405B-Instruct-quantized.w8a8
#
# Usage:
#   oumi infer -i -c configs/recipes/llama3_1/inference/405b_quantized_infer.yaml
#
# See Also:
#   - Documentation: https://oumi.ai/docs/en/latest/user_guides/infer/infer.html
#   - Config class: oumi.core.configs.InferenceConfig
#   - Config source: https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/inference_config.py
#   - Other inference configs: configs/**/inference/



model:
  model_name: "neuralmagic/Meta-Llama-3.1-405B-Instruct-quantized.w8a8"
  model_max_length: 8192
  torch_dtype_str: "bfloat16"
  attn_implementation: "sdpa"
  load_pretrained_weights: True
  trust_remote_code: True

generation:
  max_new_tokens: 2048
  batch_size: 1

engine: VLLM